server:
  port: ${HTTP_SERVER_PORT:8019}

eureka:
  instance:
    app-name: ${EUREKA_APP_NAME:user-timezone-service}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5699}/${POSTGRES_DATABASE:cherry}
    username: ${POSTGRES_USER_NAME:cherry}
    password: ${POSTGRES_PASSWORD:cherry}
  jpa:
    show-sql: 'true'
    open-in-view: 'false'
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: 'false'
        format_sql: 'false'
  flyway:
    baseline-on-migrate: true





